<?php
$linkToFileMetadata = get_option('link_to_file_metadata');
$itemFiles = $item->Files;
$useLightgallery = get_theme_option('media_lightgallery');
$mediaOnlyPrimary = get_theme_option('media_only_primary');
$mediaLinkToUrl = get_theme_option('media_link_to_url');
if ($itemFiles && $useLightgallery) {
    maobjects_queue_lightgallery_assets();
}
echo head(array('title' => metadata('item', array('Dublin Core', 'Title')), 'bodyclass' => 'items show'));
?>

<?php if (get_theme_option('hide_item_heading') != 1): ?>
    <h1><?php echo metadata('item', 'rich_title', array('no_escape' => true)); ?></h1>
<?php endif; ?>

<nav class="item-nav-buttons">
    <ul class="item-pagination navigation">
        <li id="previous-item" class="previous"><?php echo link_to_previous_item_show(); ?></li>
        <li id="next-item" class="next"><?php echo link_to_next_item_show(); ?></li>
    </ul>
</nav>

<div class="content-container">
    <div class="primary-content">
        <?php
        // Default display of all mediafiles:
        if ($itemFiles && !$useLightgallery && !$mediaOnlyPrimary) {
            echo files_for_item(array('imageSize' => get_theme_option('media_image_size') ?: 'thumbnail'), array('class' => 'element center'));
        // Default display of only primary media (first file):
        } elseif ($itemFiles && !$useLightgallery && $mediaOnlyPrimary) {
            $image = item_image(get_theme_option('media_image_size') ?: 'thumbnail', array(), 0, $item);
            $url = metadata('item', array('Item Type Metadata', 'URL'), array('no_filter' => true));
            // If a URL exists in the metadata, link the image to that URL:
            echo ($mediaLinkToUrl && $url) ? '<a class="cover" target="_blank" href="' . $url . '">' . $image . '</a>' : $image;
        // Display files using lightgallery:
        } elseif ($itemFiles && $useLightgallery) {
            echo $mediaOnlyPrimary ? lightGallery(array_splice($itemFiles, 0, 1)) : lightGallery($itemFiles);
        }
        ?>
    </div>

    <div class="secondary-content">
        <!-- Add all metadata entries: -->
        <?php echo all_element_texts('item'); ?>

        <!-- If the item belongs to a collection, create a link to that collection: -->
        <?php if (metadata('item', 'Collection Name')): ?>
        <div id="collection" class="element">
            <h3><?php echo __('Collection'); ?></h3>
            <div class="element-text"><p><?php echo link_to_collection_for_item(); ?></p></div>
        </div>
        <?php endif; ?>

        <!-- Add a list of all tags associated with the item: -->
        <?php if (metadata('item', 'has tags')): ?>
        <div id="item-tags" class="element">
            <h3><?php echo __('Tags'); ?></h3>
            <div class="element-text"><?php echo tag_string('item', 'find'); ?></div>
        </div>
        <?php endif;?>

        <div class="element">
            <div class="element-text">
                <?php fire_plugin_hook('public_items_show', array('view' => $this, 'item' => $item)); ?>
            </div>
        </div>

        <?php if ((get_theme_option('other_media') == 1) && $itemFiles): ?>
        <?php echo lightgallery_other_files($itemFiles); ?>
        <?php endif; ?>

        <!-- Add a citation for this item: -->
        <?php if (get_theme_option('show_citation') == 1): ?>
        <div id="item-citation" class="element">
            <h3><?php echo __('Citation'); ?></h3>
            <div class="element-text"><?php echo metadata('item', 'citation', array('no_escape' => true)); ?></div>
        </div>
        <?php endif; ?>

        <!-- Adds the output formats in a collapsible menu: -->
        <?php if (get_theme_option('show_outputformats') == 1): ?>
         <div id="item-output-formats" class="element">
            <h3><?php echo __('Output Formats'); ?></h3>
            <details class="element-text outputs">
                <summary class="outputs-label">
                    <span class="outputs-icon" aria-hidden="true"></span>
                    <span class="outputs-text"><?php echo __('Output Formats'); ?></span>
                    <span class="outputs-caret" aria-hidden="true"></span>
                </summary>
                <?php echo output_format_list(); ?>
            </details>
        </div>
        <?php endif; ?>
    </div>
</div>

<!-- Adds additional Item content generated by plugins, like: GeoLocation Map or Item Relations -->
<?php fire_plugin_hook('public_items_show', array('view' => $this, 'item' => $item)); ?>

<nav class="item-nav-buttons">
    <ul class="item-pagination navigation">
        <li id="previous-item" class="previous"><?php echo link_to_previous_item_show(); ?></li>
        <li id="next-item" class="next"><?php echo link_to_next_item_show(); ?></li>
    </ul>
</nav>

<?php echo foot(); ?>
